services:
  - type: web
    name: hrseinvoice
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: HRS_ADMIN_USER
        value: hrsadmin
      - key: HRS_ADMIN_PASSWORD
        value: hrsadmin101
        sync: false
