services:
  - type: web
    name: hrseinvoice
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
